CREATE TABLE "GCG_3701_Formula_Val"(
 "Laser_Sheet_Metal" NUMERIC(12,4) NOT NULL ,
 "Laser_Value_1" NUMERIC(12,4) NOT NULL ,
 "Laser_Value_2" NUMERIC(12,4) NOT NULL ,
 "Laser_Value_3" NUMERIC(12,4) NOT NULL ,
 "Deburr_Bound_box" NUMERIC(12,4) NOT NULL ,
 "Deburr_Sheet_Metal" NUMERIC(12,4) NOT NULL ,
 "Deburr_Value_1" NUMERIC(12,4) NOT NULL ,
 "Deburr_Value_2" NUMERIC(12,4) NOT NULL ,
 "TimeSave_Runtime" NUMERIC(12,4) NOT NULL ,
 "TimeSave_Value1" NUMERIC(12,4) NOT NULL ,
 "Weld_Value1" NUMERIC(12,4) NOT NULL ,
 "Polish_Value1" NUMERIC(12,4) NOT NULL ,
 "Polish_Value2" NUMERIC(12,4) NOT NULL ,
 "Inspec_Setup" NUMERIC(12,4) NOT NULL ,
 "Sheet_Metal" NUMERIC(12,4) NOT NULL ,
 "RawMat_Setup" NUMERIC(12,4) NOT NULL ,
 "RawMat_Runtime" NUMERIC(12,4) NOT NULL,
 "RAS_Setup" NUMERIC(12,4) NOT NULL );